# -*- coding: utf-8 -*-
"""fashionmnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V3sa9aca9QJd1MnS7I1Th2QP7Cl26fOL
"""

from google.colab import drive
drive.mount('/gdrive')
# %cd /gdrive

from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten
from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras.utils import np_utils
from keras import backend as k
import numpy as np
k.set_image_dim_ordering('th')
seed=7
np.random.seed(seed)

(x_train,y_train),(x_test,y_test)=fashion_mnist.load_data()

print(len(y_train))

#(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train=x_train.reshape(x_train.shape[0],1,28,28).astype('float32')
x_test=x_test.reshape(x_test.shape[0],1,28,28).astype('float32')
x_train=x_train/255
x_test=x_test/255
y_train=np_utils.to_categorical(y_train)
y_test=np_utils.to_categorical(y_test)
num_classes=y_test.shape[1]
print(num_classes)
model=Sequential()

model.add(Conv2D(32,(5,5),input_shape=(1,28,28),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(32,(5,5),input_shape=(1,14,14),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dense(num_classes,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=50, batch_size=100,verbose=2)